CC = gcc
LDFLAGS = -lopencv_legacy -lopencv_highgui -lopencv_core -lrt -lpthread -lwiringPi -lopencv_ml -lopencv_video -lopencv_imgproc -lopencv_calib3d -lopencv_objdetect -L/usr/lib
CPPFLAGS = -O3 -I/usr/include/opencv -I/usr/include/opencv2 

all: tyu3
